#!/usr/bin/env node
// ============================================================
// Landing Page Generator
// Usage: node generate.mjs "Idea name" "One paragraph describing the idea"
//
// This script calls the Claude API to generate all landing page
// copy from your idea description, then writes it to site.config.ts.
// The page is ready to deploy in seconds.
//
// Requirements:
//   ANTHROPIC_API_KEY=your-key in your environment or .env.local
// ============================================================

import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Args ──────────────────────────────────────────────────────────────────────
const [, , ideaName, ideaDescription] = process.argv;

if (!ideaName || !ideaDescription) {
  console.error("Usage: node generate.mjs \"Idea name\" \"Description of the idea\"");
  process.exit(1);
}

// ── Load API key ──────────────────────────────────────────────────────────────
let apiKey = process.env.ANTHROPIC_API_KEY;
if (!apiKey) {
  try {
    const envFile = readFileSync(path.join(__dirname, ".env.local"), "utf-8");
    const match = envFile.match(/ANTHROPIC_API_KEY=(.+)/);
    if (match) apiKey = match[1].trim();
  } catch {}
}
if (!apiKey) {
  console.error("Missing ANTHROPIC_API_KEY — add it to your environment or .env.local");
  process.exit(1);
}

// ── Slugify ───────────────────────────────────────────────────────────────────
function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

// ── Call Claude ───────────────────────────────────────────────────────────────
console.log(`\n🤖 Generating landing page copy for: ${ideaName}\n`);

const prompt = `You are helping launch a B2C SaaS side project quickly. Given the idea below, generate all landing page copy.

Idea name: ${ideaName}
Idea description: ${ideaDescription}

Return ONLY valid JSON (no markdown, no explanation) matching this exact structure:
{
  "tagline": "one line pitch under 10 words",
  "description": "two sentences for meta description",
  "hero": {
    "headline": "punchy headline, max 8 words",
    "subheadline": "one sentence expanding on the pain you solve, max 20 words"
  },
  "features": [
    { "icon": "emoji", "title": "feature title", "description": "1-2 sentence benefit-focused description" },
    { "icon": "emoji", "title": "feature title", "description": "1-2 sentence benefit-focused description" },
    { "icon": "emoji", "title": "feature title", "description": "1-2 sentence benefit-focused description" }
  ],
  "pricing": {
    "headline": "Simple pricing",
    "subheadline": "One plan. No surprises.",
    "price": "£10",
    "period": "/month",
    "earlyBirdNote": "Early bird price — locks in forever.",
    "perks": ["perk 1", "perk 2", "perk 3"],
    "ctaLabel": "Get early access"
  },
  "faq": [
    { "question": "question", "answer": "answer" },
    { "question": "question", "answer": "answer" },
    { "question": "question", "answer": "answer" }
  ]
}`;

const response = await fetch("https://api.anthropic.com/v1/messages", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "x-api-key": apiKey,
    "anthropic-version": "2023-06-01",
  },
  body: JSON.stringify({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 1500,
    messages: [{ role: "user", content: prompt }],
  }),
});

if (!response.ok) {
  const err = await response.text();
  console.error("Claude API error:", err);
  process.exit(1);
}

const data = await response.json();
const raw = data.content[0].text.trim();

let generated;
try {
  generated = JSON.parse(raw);
} catch {
  console.error("Failed to parse Claude response as JSON:\n", raw);
  process.exit(1);
}

// ── Write site.config.ts ──────────────────────────────────────────────────────
const subdomain = slugify(ideaName);
const configPath = path.join(__dirname, "config", "site.config.ts");

const config = `// ============================================================
// SITE CONFIG — auto-generated by generate.mjs
// Idea: ${ideaName}
// Generated: ${new Date().toISOString()}
// ============================================================

export const siteConfig = {
  name: ${JSON.stringify(ideaName)},
  tagline: ${JSON.stringify(generated.tagline)},
  description: ${JSON.stringify(generated.description)},
  subdomain: ${JSON.stringify(subdomain)},
  twitterHandle: "",

  hero: {
    headline: ${JSON.stringify(generated.hero.headline)},
    subheadline: ${JSON.stringify(generated.hero.subheadline)},
    ctaLabel: "Join the waitlist",
    ctaNote: "Free to join. No spam, ever.",
  },

  features: ${JSON.stringify(generated.features, null, 4)},

  pricing: {
    headline: ${JSON.stringify(generated.pricing.headline)},
    subheadline: ${JSON.stringify(generated.pricing.subheadline)},
    price: ${JSON.stringify(generated.pricing.price)},
    period: ${JSON.stringify(generated.pricing.period)},
    earlyBirdNote: ${JSON.stringify(generated.pricing.earlyBirdNote)},
    perks: ${JSON.stringify(generated.pricing.perks)},
    ctaLabel: ${JSON.stringify(generated.pricing.ctaLabel)},
    stripeLink: "", // add your Stripe payment link here
  },

  faq: ${JSON.stringify(generated.faq, null, 4)},

  footer: {
    builtBy: "tinylabs.tech",
    builtByUrl: "https://tinylabs.tech",
  },
};
`;

writeFileSync(configPath, config, "utf-8");

console.log(`✅ site.config.ts updated`);
console.log(`🌐 Subdomain: ${subdomain}.tinylabs.tech`);
console.log(`\nNext steps:`);
console.log(`  1. Run: npm run dev  — to preview locally`);
console.log(`  2. Push to GitHub — Vercel auto-deploys`);
console.log(`  3. Add subdomain in Vercel: ${subdomain}.tinylabs.tech`);
console.log(`  4. Add Stripe link to config once you create a payment link\n`);
